Summary: Python 2, 3.4, 3.5, pandas udf, pyarrow, zeppelin spark interpreter, date object, AttributeError, dt accessor 

Description: pandas udf, dataframe, pyarrow, 0.17.0, ARROW_PRE_0_15_IPC_FORMAT, zeppelin spark interpreter, error, Task 0, stage 19.0, executor 1, PythonException, arrow_to_pandas, pa.Table.from_batches, itercolumns, _check_series_convert_date, AttributeError, Can only use .dt accessor with datetimelike values.